device: "cpu"             # or "cpu"
num_samples: 100
dataset_name: "clane9/imagenet-100" #"cifar100" #
split: "validation" # train test val validation
model_id: "ViT-B/16"
visualize: False
# only to collect data
keep_pct: 0.5 # 0 to 1 


